{
  "extends": "stylelint-config-standard",
  "rules": {
    "number-leading-zero": null,
    "at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": [
          "mixin",
          'extend',
          "define-mixin",
          "include",
          "content",
          "rules",
          "function",
          "return",
          "if",
          "else",
          "for"
        ]
      }
    ]
  }
}